name: Release Pipeline

on:
  push:
    branches:
      - release

permissions:
  contents: write   # Ensures write access to create tags and upload artifacts

jobs:
  create-release-tag:
    runs-on: ubuntu-latest  # Create a release tag
    outputs:
      RELEASE_TAG: ${{ steps.create_release_tag.outputs.RELEASE_TAG }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get project version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release Tag
        id: create_release_tag
        run: |
          # Generate a version tag based on the branch or other logic (e.g., using version from POM)
          TAG="${{ env.VERSION }}.${{ github.run_number }}"
          echo "Created tag: $TAG"
          
          # Create a tag and push it to the repository
          git tag $TAG
          git push origin $TAG

          # Set release tag for other jobs
          echo "RELEASE_TAG=$TAG" >> $GITHUB_OUTPUT

  release-linux:
    runs-on: ubuntu-latest
    needs: create-release-tag
    env:
      RELEASE_TAG: ${{ needs.create-release-tag.outputs.RELEASE_TAG }}
      VERSION: ${{ needs.create-release-tag.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, test, and package with Maven
        run: mvn clean package --batch-mode

      - name: Package application as self-contained Linux installer
        run: |
          jpackage --input target/ --name TrafficSim --main-jar traffic_sim_with_dep.jar --main-class com.example.App --type deb --dest target/ --vendor "SWE Group 32"

      - name: Upload Linux package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.deb
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    runs-on: windows-latest
    needs: create-release-tag
    env:
        RELEASE_TAG: ${{ needs.create-release-tag.outputs.RELEASE_TAG }}
        VERSION: ${{ needs.create-release-tag.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, test, and package with Maven
        run: mvn clean package --batch-mode

      - name: Package application as self-contained Windows installer
        run: |
          jpackage --input target/ --name TrafficSim --main-jar traffic_sim_with_dep.jar --main-class com.example.App --type exe --dest target/ --vendor "SWE Group 32"

      - name: Upload Windows package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.exe
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos:
    runs-on: macos-latest
    needs: create-release-tag
    env:
        RELEASE_TAG: ${{ needs.create-release-tag.outputs.RELEASE_TAG }}
        VERSION: ${{ needs.create-release-tag.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, test, and package with Maven
        run: mvn clean package --batch-mode

      - name: Package application as self-contained macOS installer
        run: |
          jpackage --input target/ --name TrafficSim --main-jar traffic_sim_with_dep.jar --main-class com.example.App --type dmg --dest target/ --vendor "SWE Group 32"

      - name: Upload macOS package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.dmg
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}